### PR TITLE
update the proposal

### PR DESCRIPTION
**Pull request by feng-tao**

### CODE REVIEW

**Comment by feng-tao** [comment]
cc @ibrahimhaddad @markgrover

**Comment by markgrover** [comment]
+1

**Comment by Golodhros** [comment]
+1

**Comment by feng-tao** [comment]
@ibrahimhaddad could you take a look? thanks

**Comment by markgrover** [comment]
+1 on adding both Allison and Mariusz.

cc @ibrahimhaddad would love your +1 here too so we can merge it.

**Comment by feng-tao** [comment]
ping @ibrahimhaddad

**Comment by feng-tao** [comment]
@ibrahimhaddad

**Pull request merged**
